apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: silky-aphid-nodejs 
  janus-idp.io/tekton: silky-aphid-nodejs
  backstage.io/kubernetes-id: silky-aphid-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: silky-aphid-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  