apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: silky-aphid-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: silky-aphid-nodejs 
  name: silky-aphid-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: silky-aphid-nodejs 
